### ISSUE TITLE
Default settings values are not changeable.

### ISSUE THREAD

**Issue by babsey** [nest-desktop/nest-desktop#131]
In NEST Desktop the default port number for NEST Simulator is 5000.
However, there was a request that they have to manually change the port number in the settings.

Every setting values are integrated  in js file in the production. 
Thus, it was not possible to set default value before starting NEST Desktop.

An idea would be to outsource the settings of NEST Simulator to JSON file in public folder.

**Comment by jens-br** [comment]
Feature was introduced in #132
