### ISSUE TITLE
Solutions or replacements for packages with security issues

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#158]
`dat.gui` seems to be abandoned (https://github.com/dataarts/dat.gui#readme) and has a security issue (severity: high):
![grafik](https://user-images.githubusercontent.com/53972736/142733290-50d46857-3fe3-4826-8851-2e19bd6f370d.png)

We should look for alternatives (like the ones in https://gist.github.com/SMUsamaShah/71d5ac6849cdc0bffff4c19329e9d0bb)

A solution for `glob-parent` should also be considered:
![grafik](https://user-images.githubusercontent.com/53972736/142733297-3620b502-36b2-41cb-9629-62d4bcafd8d8.png)

**Comment by babsey** [comment]
`dat.gui` is now removed.

**Comment by jens-br** [comment]
As mentioned [here](https://github.com/nest-desktop/nest-desktop/pull/212#issuecomment-1011160809), the rest of these problems depend of the problematic packages mentioned in `package.json` - so we will have a another look at this issue when we can finally do the upgrade.

**Comment by babsey** [comment]
The last update of this issue has been 2 years and I did not register similar problem since.
