### ISSUE TITLE
Vuetify 3.0

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#207]
Since Vuetify 3.0 seems to be  [ready in February](https://vuetifyjs.com/en/introduction/roadmap/), we should consider to include it in NEST Desktop 3.2.

**Comment by jens-br** [comment]
There might be some problems with Vuetify 3, as mentioned in https://www.reddit.com/r/vuejs/comments/t2vcxy/discussion_what_the_hell_is_going_on_with_vuetify/ and given that the progress on their [GitHub](https://github.com/vuetifyjs/vuetify) repo is currently quite slow. Therefore, it might be delayed a bit.

**Comment by babsey** [comment]
Vuetify 3 and Vue 3 is included in NEST Desktop v4.0.
