### ISSUE TITLE
Can't connect nodes on EBRAINS prototype

### ISSUE THREAD

**Issue by abigailm** [nest-desktop/nest-desktop#319]
When using the EBRAINS prototype (https://nest-desktop.apps.hbp.eu/#/) I can create nodes but not connect them. When I click on the node 'handle', this is interpreted as a select-and-move of the node.

When using NEST Desktop locally (installed using the Docker Compose route) everything works as intended.
Macbook Pro/ Catalina 10.15.7/ Chrome v98.0.4758.109

**Comment by jens-br** [comment]
Thank you very much for your feedback! :+1: I tested it right now, but I could not reproduce that error: ![Connect-Node](https://user-images.githubusercontent.com/53972736/158219812-a9f4e58c-cc0d-4563-ab6f-ccfe143e1da0.gif) 

- [ ] Sometimes it could work to use the ALT key for connecting.
- [ ] You used the EBRAINS NEST Desktop service on version 3.1.2, right?
- [ ] Could you provide a screenshot or a copy-paste dump of the console logfile (opens with F12)?
- [ ] Sometimes it helps to export your projects (if you have some which you want to keep) and to clear the cookies. If you have a cookie which was created by an older NEST Desktop version, this is not unlikely to cause errors.

Could you try these options/provide the additional information mentioned above? This would help us a lot in identifying the source of that problem!

**Comment by jens-br** [comment]
@abigailm Hi, do you have updates on this? :)

**Comment by babsey** [comment]
@abigailm 

I deployed pre-release app on https://nest-desktop.apps-dev.hbp.eu. Can you check if this issue still persists?

**Comment by babsey** [comment]
The release v4.0 fixes this connection action issue.
