### ISSUE TITLE
Replace `v-tooltip` by `title`

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#408]
**Is your feature request related to a problem? Please describe.**
Currently, we have a wild mix of places where `v-tooltip` and `title` are used.

**Describe the solution you'd like**
Therefore, we would like to drop the `v-tooltip` in favor of `title.

**Describe alternatives you've considered**
On the one hand, `v-tooltip` has a better design than `title`. However, `title` is much more efficient and much faster, even on quite recent machines.

**Additional context**
N/A

**Comment by simarpreetsingh-019** [comment]
Can you share some more information about this issue?

**Comment by jens-br** [comment]
This issue has been resolved with #453 .
