### ISSUE TITLE
Type Handling and Typing Strategy

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#42]
- [x] The typing of some variables is currently done by setting these types to `any`. It might be worth to have a closer look at these cases and try to find a solution for them.
- [x] General strategies for typing like
[https://stackoverflow.com/questions/37263357/how-to-declare-and-import-typescript-interfaces-in-a-separate-file#37274839](url) (a global `types.ts` file)
or
[https://stackoverflow.com/questions/36633033/how-to-organize-typescript-interfaces#36636368](url) (`.d.ts` files)
could lead to some universal approaches here. It should be discussed which types these global file(s) should contain (and which should be kept local for performance reasons).

Examples:

- `activityData`, `data`, `event` (multiple and different occurrences)
- `layer`, `trail` : src/core/activity/animationScenes/activityAnimationSceneBox.ts, etc.
- `scene`: src/core/activity/activityAnimationGraph.ts
-  `route` src/components/navigation/NavigationTemporary.vue
- ... (to be continued)

**Comment by babsey** [comment]
In NEST Desktop v4.0 many variables has been defined as non-any type as possible.
I added `types.ts` to collect all class types.
