### ISSUE TITLE
Docs: Incorrect rendering in the Snap installation guide

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#523]
**Describe the bug**
The setup for Snap (.../user/setup/index.html#snap-linux)  in the docs is not rendered correctly.

**To Reproduce**

1. Visit the Snap page
2. See error

**Expected behavior**
The rendering should be correct.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53972736/219078839-435cb977-385b-4bdb-92df-fd251fdb4871.png)

**Desktop (please complete the following information):**
OS-independent (?)

**Smartphone (please complete the following information):**
OS-independent (?)

**Additional context**
n/a

**Comment by babsey** [comment]
The issue of documentation should be addressed in https://github.com/nest-desktop/nest-desktop-docs/issues.

But this issue has been resolved.
