### ISSUE TITLE
Allow complex dynamic publicpaths

### ISSUE THREAD

**Issue by jhgoebbert** [nest-desktop/nest-desktop#572]
**Is your feature request related to a problem? Please describe.**
I would like to run the NEST Desktop behind an http-proxy on a dynamically generated sub-url  
like, https://portal.de/userid/hash/nest-desktop
The userid and hash changes with every new session and is not predictable in advance.

**Describe the solution you'd like**
This is possible (I tried it) by adding
`publicPath: './'`
instead of 
`publicPath: process.env.BASE_URL,`
at https://github.com/nest-desktop/nest-desktop/blob/dev/vue.config.js#L10
as documented at https://cli.vuejs.org/config/#publicpath

**Comment by babsey** [comment]
Many thanks to reporting this issue.

We fixes the bug and open PR #574.

How did you install NEST Desktop (pip, conda, docker)?

**Comment by jhgoebbert** [comment]
Great. Thank you for merging it!  

I created an easybuild script which runs `yarn install && yarn build && pip install` to build and install nest-desktop (as a module on our systems).
