### ISSUE TITLE
Code Documentation Framework

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#59]
It might be a good idea to change to a solid code documentation framework. This would pose the option to generate a webpage containing all our documentation and give easy hints for documentation.

A good list can be found at [https://vue-community.org/guide/ecosystem/documentation.html](https://vue-community.org/guide/ecosystem/documentation.html). Vue Styleguidist ([https://vue-styleguidist.github.io/docs/Documenting.html#code-comments](https://vue-styleguidist.github.io/docs/Documenting.html#code-comments)) and Vuese (c.f [https://dev.to/berniwittmann/quick--easy-documentation-generation-for-vuejs-components-7k6](https://dev.to/berniwittmann/quick--easy-documentation-generation-for-vuejs-components-7k6)) looked interesting, Vue Styleguidist has the major advantage to use plain JSDoc comments we are already using, so this should be not a breaking change.

I tested Vue Styleguidist and jsdoc-vuejs, but both seem to struggle with the Composition API. Therefore, I would suggest to address this at earliest in summer, rather autumn (-> task for version >=3.1).

**Comment by babsey** [comment]
Closed because of many points:
- vue-community.org and vuese.org do no longer exist anymore.
- vue-styleguidist.github.io uses `vue-cli` which is replaced by `vite` in NEST Desktop v4.0

**Comment by babsey** [comment]
By the ways, I keep add code documentation for all/many functions and classes.
