### ISSUE TITLE
docker-compose.yml still contains an older NEST version

### ISSUE THREAD

**Issue by steffengraber** [nest-desktop/nest-desktop#591]
**Describe the bug**

`docker-registry.ebrains.eu/nest/nest-simulator:3.4 `is still loaded in the docker-compose.yml. The NEST images are now back on Dockerhub. 
The current image can be found here:

    nest/nest-simulator:3.6

**Comment by babsey** [comment]
The release v4.0 updates `docker-compose.yml`. It contains the latest NEST image.
