### ISSUE TITLE
Upgrade Plotly

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#78]
Plotly needs to be upgraded to version 2.0.0. The following problem needs to be addressed for this:

- [x] The exported images contain artifacts: In column charts, the text "auto" is contained for every column.

**Comment by babsey** [comment]
The issue of artifacts ('auto' in columns) is fixed.

**Comment by babsey** [comment]
Plotly is upgraded to v2.0.0 in Commit 20d6d59 (June 23rd).
