### ISSUE TITLE
Upgrade @vue/eslint-config-typescript

### ISSUE THREAD

**Issue by jens-br** [nest-desktop/nest-desktop#79]
An upgrade of the package `@vue/eslint-config-typescript `should be considered: It is currently on version 4.0.0 (2019 or before), the current version would be 7.0.0. A warning of possible problems is given at every compilation.

**Comment by babsey** [comment]
I assume this issue has been resolved.

See https://github.com/nest-desktop/nest-desktop/blob/993ef80d812e3aeecd3657d1c3e3cb54ed5ba9d5/package.json#L70

**Comment by jens-br** [comment]
Included in #157.
